version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: gotransactions
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: