
CREATE TABLE public.user (
    id INT PRIMARY KEY,
    username VARCHAR(300)
);

CREATE TABLE wallet (
    id INT PRIMARY KEY,
    creation_date DATE,
    balance FLOAT,
    currency VARCHAR(100),
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES public.user(id)
);

CREATE TABLE transaction (
    id INT PRIMARY KEY,
    primary_wallet_id INT,
    recipient_wallet_id INT,  
    transaction_type VARCHAR(50),
    amount FLOAT,
    transaction_date DATE,
    FOREIGN KEY (primary_wallet_id) REFERENCES wallet(id),
    FOREIGN KEY (recipient_wallet_id) REFERENCES wallet(id) 
);

-- Change type to decimal
ALTER TABLE public.transaction 
ALTER COLUMN amount type DECIMAL; 

ALTER TABLE public.wallet 
ALTER COLUMN balance type DECIMAL; 

-- Make ids auto increment
ALTER TABLE public.user
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE wallet
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.transaction
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;